default:
   image: pulumi/pulumi-nodejs
stages:
  - unit-test
  - provide-infrastructure
  - acceptance-test
  - destroy-infrastructure

unit-test:
  stage: unit-test
  script:
    - cd infAsCode/create-role
    - npm i
    - npm test
    - cd ..

provide-infrastructure:
  stage: provide-infrastructure
  script:
    - cd infAsCode/create-role
    - npm i
    - pulumi login
    - pulumi stack select dev
    - pulumi up -y
    - export AWS_ACCESS_KEY_ID="$(pulumi stack output  accessKeyId)"
    - export AWS_SECRET_ACCESS_KEY="$(pulumi stack output --show-secrets secretAccessKey)"
    - export ROLE_TO_ASSUME_ARN="$(pulumi stack output roleArn)"
    - cd ../assume-role
    - npm i
    - pulumi stack select dev
    - pulumi config set roleToAssumeARN "$(echo $ROLE_TO_ASSUME_ARN)"
    - pulumi up -y

acceptance-test:
  stage: acceptance-test
  script:
    - cd acceptancetest
    - npm i
    - npm test
    - cd ..
   
destroy-infrastructucture:
   stage: destroy-infrastructure
   script:
     - cd infAsCode/create-role
     - npm i
     - pulumi login
     - pulumi stack select dev
     - pulumi destroy -y