default:
   image: pulumi/pulumi-nodejs
stages:
  - provide
  - destroy

provide-infrastructure:
  stage: provide
  script:
    - npm i
    - pulumi login
    - export PULUMI_ACCESS_TOKEN="$PULUMI_ACCESS_TOKEN"
    - pulumi login
    - pulumi stack select test
    - pulumi up -y

destroy-infrastructucture:
   stage: destroy
   script:
     - npm i
     - export PULUMI_ACCESS_TOKEN="$PULUMI_ACCESS_TOKEN"
     - pulumi login
     - pulumi stack select test
     - pulumi destroy -y