default:
   image: pulumi/pulumi-nodejs
stages:
  - unit-test
  - provide
  - acceptance-test
  - destroy

unit-test:
  stage: unit-test
  script:
    - cd infAsCode/create-role
    - npm i
    - npm test
    - cd ..

provide-infrastructure:
  stage: provide
  script:
    - cd infAsCode/create-role
    - npm i
    - pulumi login
    - pulumi stack select dev
    - pulumi up -y
    - export AWS_ACCESS_KEY_ID="$(pulumi stack output  accessKeyId)"
    - export AWS_SECRET_ACCESS_KEY="$(pulumi stack output --show-secrets secretAccessKey)"
    - cd ../assume-role
    - npm i
    - pulumi stack select dev
    - pulumi up -y

acceptance-test:
  stage: acceptance-test
  script:
    - cd acceptancetest
    - npm i
    - npm test
    - cd ..
   
destroy-infrastructucture:
   stage: destroy
   script:
     - cd infAsCode
     - npm i
     - pulumi login
     - pulumi stack select dev
     - pulumi destroy -y
     - cd