default:
   image: pulumi/pulumi-nodejs
stages:
  - provide
  - acceptance-test
  - destroy

provide-infrastructure:
  stage: provide
  script:
    - npm i
    - pulumi login
    - export PULUMI_ACCESS_TOKEN="$PULUMI_ACCESS_TOKEN"
    - pulumi login
    - pulumi stack select dev
    - pulumi up -y

acceptance-test:
  stage: acceptance-test
  script:
    -npm i
    -npm run acceptancetest
   

destroy-infrastructucture:
   stage: destroy
   script:
     - npm i
     - export PULUMI_ACCESS_TOKEN="$PULUMI_ACCESS_TOKEN"
     - pulumi login
     - pulumi stack select dev
     - pulumi destroy -y